---
#CONFIG VERSION
#DO NOT CHANGE THIS VALUE
version: 2

#ID of the relic. (Item given to player)
relic-id: 399

#List of Block IDs that relics can be found with.
block-ids:
  - 14
  - 15
  - 21
  - 56
  - 73

#List of supported worlds to find relics.
#Use "*" for all worlds
worlds: ["*"]

#Choose if the message is shown when a user finds a relic
found-message-enabled: true
#How the message is received. Options: title, tip or message
message-type: "message"
#Choose if particles shown when a player finds/opens a relic
particles-enabled: true

#Rarity of Relic. Do not change this!
common:
  #Shown on relic item
  name: "&l&eUnCommon &dRelic"
  #Title shown to player. Use "\n" for a new line!
  title: "&bCongrats!\n&7You found a common relic!"
  #Tip shown to player.
  tip: "&bCongrats! &7You found a common relic!"
  #Message shown to player.
  message: "&l&2..&e[&dRelic&e]&2..&r&f &bCongrats! &fYou found a UnCommon relic!"
  #Lore for relic
  lore: "&7Right Click to claim your rewards!"
  #Chance to get the relic. 10 = 5%
  chance: 1
  #List of commands. Use {player} for the player.
  #A command will be chosen at random from this list.
  commands:
    - "give {player} 384 8" # XP-BOTTLES
    - "give {player} 42 10" # IRON-BLOCKS
    - "moneypouch 2 {player}"
    - "sellwand {player} 4"
    - "key common {player} 1"

#Rarity of Relic. Do not change this!
rare:
  #Shown on relic item
  name: "&l&eSpyro &dRelic"
  #Title shown to player
  title: "&bCongrats!\n&7You found a rare relic!"
  #Tip shown to player.
  tip: "&bCongrats! &7You found a rare relic!"
  #Message shown to player.
  message: "&l&2..&e[&dRelic&e]&2..&r&f &bCongrats! &fYou found a Spyro relic!"
  #Lore for relic
  lore: "&7Right Click to claim your rewards!"
  #Chance to get the relic.  10 = 5%
  chance: 1
  #List of commands. Use {player} for the player.
  #A command will be chosen at random from this list.
  commands:
    - "give {player} 384 16" # XP-BOTTLES
    - "give {player} 41 10" # GOLD-BLOCKS
    - "moneypouch 3 {player}"
    - "sellwand {player} 8"
    - "key common {player} 1"
    - "key exotic {player} 1"

#Rarity of Relic. Do not change this!
epic:
  #Shown on relic item
  name: "&l&ePheonix &dRelic"
  #Title shown to player
  title: "&bCongrats!\n&7You found an epic relic!"
  #Tip shown to player.
  tip: "&bCongrats! &7You found an epic relic!"
  #Message shown to player.
  message: "&l&2..&e[&dRelic&e]&2..&r&f &bCongrats! &fYou found a Pheonix relic!"
  #Lore for relic
  lore: "&7Right Click to claim your rewards!"
  #Chance to get the relic.  10 = 5%
  chance: 1
  #List of commands. Use {player} for the player.
  #A command will be chosen at random from this list.
  commands:
    - "give {player} 384 32" # XP-BOTTLES
    - "give {player} 133 10" # EMERALD-BLOCKS
    - "moneypouch 4 {player}"
    - "sellwand {player} 12"
    - "condensewand {player} 12"
    - "key common {player} 1"
    - "key exotic {player} 1"
    - "key rare {player} 1"
    - "key potions {player} 1"

#Rarity of Relic. Do not change this!
legendary:
  #Shown on relic item
  name: "&l&eApollo &dRelic"
  #Title shown to player
  title: "&bCongrats!\n&7You found a legendary relic!"
  #Tip shown to player.
  tip: "&bCongrats! &7You found a legendary relic!"
  #Message shown to player.
  message: "&l&2..&e[&dRelic&e]&2..&r&f &bCongrats! &fYou found a Apollo relic!"
  #Lore for relic
  lore: "&7Right Click to claim your rewards!"
  #Chance to get the relic.  10 = 5%
  chance: 1
  #List of commands. Use {player} for the player.
  #A command will be chosen at random from this list.
  commands:
    - "give {player} 384 64" # XP-BOTTLES
    - "give {player} 57 10" # DIAMOND-BLOCKS
    - "moneypouch 5 {player}"
    - "sellwand {player} 16"
    - "condensewand {player} 16"
    - "key common {player} 1"
    - "key exotic {player} 1"
    - "key rare {player} 1"
    - "key spawners {player} 1"
    - "key potions {player} 1"
...
